In [ ]:
from pathlib import Path
import ProjectDefaults as defaults
import pandas as pd
from IPython.display import Image, display
from src.Anomaly.Thresholds.Incremental.DspotThreshold import (
    DspotConfig,
    DspotThreshold,
)
from src.Data.OnlineImputers import (
    IncrementalMeanImputer,
    ZeroOnlineImputer,
)
from src.Data.OnlineNormalizers import IncrementalZScoreNormalizer, NoOnlineNormalizer
from src.Data.Processor import DataStreamProcessor
from src.Optimization import (
    DatasetProfile,
    ModelProfile,
    OptimizationConfig,
    OptunaStreamOptimizer,
)
from src.Pipeline.TrainingPipeline import TrainingPipeline
from src.Training.TrainAllStrategy import TrainAllStrategy

# Adaptative Isolation Forest

## Parâmetros

In [ ]:
# Perfis compartilhados com a otimização
datasetProfile = DatasetProfile()
modelProfile = ModelProfile()

targetColumn = datasetProfile.targetColumn
selectedFeatures = list(datasetProfile.selectedFeatures) if datasetProfile.selectedFeatures is not None else None
removedFeatures = list(datasetProfile.removedFeatures) if datasetProfile.removedFeatures is not None else None

modelCode = modelProfile.code
modelParameters = dict(modelProfile.parameters)


# Configuração convencional centralizada em ProjectDefaults.py.
initialWarmupSize = defaults.DEFAULT_INITIAL_WARMUP_SIZE

dspotCalibrationWindowSize = defaults.DEFAULT_DSPOT_CALIBRATION_WINDOW
dspotDriftDepth = defaults.DEFAULT_DSPOT_DRIFT_DEPTH
scoreWindowSizes = list(defaults.DEFAULT_SCORE_WINDOW_SIZES)
dspotScoreSources = list(defaults.DEFAULT_DSPOT_SCORE_SOURCES)

availableImputers = {
    "zero": ZeroOnlineImputer,
    "incrementalMean": IncrementalMeanImputer,
}
imputerFactories = {
    name: availableImputers[name]
    for name in defaults.DEFAULT_IMPUTER_NAMES
}

def normalizerFactory():
    if defaults.DEFAULT_NORMALIZER_NAME == "none":
        return NoOnlineNormalizer()
    if defaults.DEFAULT_NORMALIZER_NAME == "incrementalZScore":
        return IncrementalZScoreNormalizer(**defaults.DEFAULT_NORMALIZER_PARAMETERS)
    raise ValueError(f"Normalizador desconhecido: {defaults.DEFAULT_NORMALIZER_NAME}")

metricsWindowSize = defaults.DEFAULT_METRICS_WINDOW_SIZE
outputPath = defaults.DEFAULT_OUTPUT_ROOT
seed = defaults.DEFAULT_SEED

dspotConfig = DspotConfig(**dict(defaults.DEFAULT_DSPOT_PARAMETERS))

## Treinamento e Otimização

### TREINAMENTO

In [ ]:
# Configuração dos datasets e execuções dos cenários

scenarioNames = list(defaults.DEFAULT_DATASET_SCENARIOS)
attackScales = list(defaults.DEFAULT_ATTACK_SCALES)
datasetsRoot = defaults.DEFAULT_DATA_ROOT

datasetPaths = [
    datasetsRoot
    / scenarioName
    / f"{scenarioName}_{attackScale}.csv"
    for scenarioName in scenarioNames
    for attackScale in attackScales
]


missingDatasets = [
    path
    for path in datasetPaths
    if not path.exists()
]

if missingDatasets:
    missingText = "\n".join(
        str(path.resolve())
        for path in missingDatasets
    )

    raise FileNotFoundError(
        "Os seguintes datasets não foram encontrados:\n"
        f"{missingText}"
    )


totalExecutions = (
    len(datasetPaths)
    * len(imputerFactories)
    * len(dspotScoreSources)
)

print(f"Datasets encontrados: {len(datasetPaths)}")
print(f"Imputadores: {len(imputerFactories)}")
print(f"Fontes de score: {len(dspotScoreSources)}")
print(f"Total de execuções: {totalExecutions}")


resultDspotAll = {}
executionRecords = []
currentExecution = 0


for datasetPath in datasetPaths:
    datasetName = datasetPath.stem
    dataframe = pd.read_csv(datasetPath)

    print("\n" + "=" * 80)
    print(f"Dataset: {datasetName}")
    print(f"Arquivo: {datasetPath}")
    print(f"Instâncias originais: {len(dataframe)}")
    print("=" * 80)

    processor = DataStreamProcessor(
        logging=True,
        selected_features=selectedFeatures,
        removed_features=removedFeatures,
    )

    (
        stream,
        targetNames,
        featureNames,
        labelNames,
    ) = processor.create_stream(
        dataframe,
        target_label_col=targetColumn,
        binary_label=datasetProfile.binaryLabel,
    )

    resultDspotAll[datasetName] = {}

    for imputerName, imputerFactory in imputerFactories.items():
        resultDspotAll[datasetName][imputerName] = {}

        for thresholdScoreSource in dspotScoreSources:
            currentExecution += 1

            executionDescription = (
                f"[{currentExecution:03d}/{totalExecutions:03d}] "
                f"Dataset={datasetName} | "
                f"Imputer={imputerName} | "
                f"Score={thresholdScoreSource} | "
                "Strategy=TrainAll"
            )

            print(f"\nIniciando: {executionDescription}")

            try:
                pipeline = TrainingPipeline(
                    stream=stream,
                    datasetName=datasetName,
                    modelCode=modelCode,
                    threshold=DspotThreshold(dspotConfig),
                    labelNames=labelNames,
                    modelParameters=modelParameters,
                    imputer=imputerFactory(),
                    normalizer=normalizerFactory(),
                    trainingStrategy=TrainAllStrategy(),
                    scoreWindowSizes=scoreWindowSizes,
                    metricsWindowSize=metricsWindowSize,
                    outputPath=outputPath,
                    normalClassIndex=0,
                    seed=seed,
                    generatePlots=True,
                    initialWarmupSize=initialWarmupSize,
                    thresholdScoreSource=thresholdScoreSource,
                )

                executionResult = pipeline.run()

                streamMetrics = (
                    executionResult["streamMetricsFrame"]
                    .iloc[0]
                )

                # Mantém somente os caminhos necessários.
                # Os DataFrames completos não ficam acumulados na memória.
                resultDspotAll[datasetName][imputerName][
                    thresholdScoreSource
                ] = {
                    "runDirectory": executionResult[
                        "runDirectory"
                    ],
                    "streamMetricsPath": executionResult[
                        "streamMetricsPath"
                    ],
                }

                executionRecords.append({
                    "dataset": datasetName,
                    "instances": int(
                        streamMetrics["totalInstances"]
                    ),
                    "evaluatedInstances": int(
                        streamMetrics["evaluatedInstances"]
                    ),
                    "attackRatioPercent": float(
                        streamMetrics["attackRatioPercent"]
                    ),
                    "imputer": imputerName,
                    "scoreSource": thresholdScoreSource,
                    "trainingStrategy": "all",
                    "precision": float(
                        streamMetrics["precision"]
                    ),
                    "recall": float(
                        streamMetrics["recall"]
                    ),
                    "f1": float(
                        streamMetrics["f1"]
                    ),
                    "fp": int(
                        streamMetrics["fp"]
                    ),
                    "fn": int(
                        streamMetrics["fn"]
                    ),
                    "status": "Concluída",
                    "error": "",
                    "resultPath": executionResult[
                        "streamMetricsPath"
                    ],
                })

                print(
                    f"Concluída: {executionDescription} | "
                    f"F1={streamMetrics['f1']:.6f}"
                )

            except Exception as error:
                resultDspotAll[datasetName][imputerName][
                    thresholdScoreSource
                ] = None

                executionRecords.append({
                    "dataset": datasetName,
                    "instances": len(dataframe),
                    "evaluatedInstances": pd.NA,
                    "attackRatioPercent": pd.NA,
                    "imputer": imputerName,
                    "scoreSource": thresholdScoreSource,
                    "trainingStrategy": "all",
                    "precision": pd.NA,
                    "recall": pd.NA,
                    "f1": pd.NA,
                    "fp": pd.NA,
                    "fn": pd.NA,
                    "status": "Erro",
                    "error": str(error),
                    "resultPath": "",
                })

                print(f"Erro: {executionDescription}")
                print(f"Motivo: {error}")


executionSummary = pd.DataFrame(executionRecords)

completedExecutions = int(
    executionSummary["status"]
    .eq("Concluída")
    .sum()
)

failedExecutions = int(
    executionSummary["status"]
    .eq("Erro")
    .sum()
)

print("\nResumo final")
print(f"Execuções concluídas: {completedExecutions}")
print(f"Execuções com erro: {failedExecutions}")

display(executionSummary)

### OTIMIZAÇÃO - Blocos de 200 instâncias de ataque

In [ ]:
optimizationConfig = OptimizationConfig(
    dataRoot=Path("data/15k"),
    outputRoot=Path("output/Optimization"),
    scenarios=(
        "Adaptation",
        "Consistency",
        "Generalization",
        "Recurrence",
    ),
    blockSize=200,
    nTrials=100,
    topK=10,
    metricsWindowSize=100,
    initialWarmupSize=initialWarmupSize,
    seed=seed,
    optunaSeed=seed,
)

optimizer = OptunaStreamOptimizer(
    config=optimizationConfig,
    datasetProfile=datasetProfile,
    modelProfile=modelProfile,
)

optimizationResult = optimizer.run()

#### Execução 4x4 para verificar estabilidade de parâmetros otimizados

In [5]:
datasetProfile = DatasetProfile()
modelProfile = ModelProfile()

targetColumn = datasetProfile.targetColumn

selectedFeatures = (
    list(datasetProfile.selectedFeatures)
    if datasetProfile.selectedFeatures is not None
    else None
)

removedFeatures = (
    list(datasetProfile.removedFeatures)
    if datasetProfile.removedFeatures is not None
    else None
)

modelCode = modelProfile.code

initialWarmupSize = defaults.DEFAULT_INITIAL_WARMUP_SIZE
metricsWindowSize = defaults.DEFAULT_METRICS_WINDOW_SIZE
outputPath = defaults.DEFAULT_OUTPUT_ROOT
seed = defaults.DEFAULT_SEED


def imputerFactory():
    return IncrementalMeanImputer()


def normalizerFactory():
    return IncrementalZScoreNormalizer(
        **defaults.DEFAULT_NORMALIZER_PARAMETERS
    )

In [6]:
datasetsRoot = defaults.DEFAULT_DATA_ROOT

scenarioDatasets = {
    "Adaptation": (
        datasetsRoot
        / "Adaptação"
        / "Adaptação_200.csv"
    ),
    "Consistency": (
        datasetsRoot
        / "Consistência"
        / "Consistência_200.csv"
    ),
    "Generalization": (
        datasetsRoot
        / "Generalização"
        / "Generalização_200.csv"
    ),
    "Recurrence": (
        datasetsRoot
        / "Recorrência"
        / "Recorrência_200.csv"
    ),
}


parameterProfiles = {
    "Adaptation": {
        "modelParameters": {
            "window_size": 512,
            "n_trees": 200,
            "height": 13,
            "m_trees": 15,
            "weights": 0.3132498798988575,
        },
        "scoreMode": "movingAverage",
        "movingAverageWindow": 10,
        "dspot": {
            "calibrationWindow": 650,
            "driftDepth": 85,
            "initialQuantile": 0.9152126768642046,
            "risk": 0.0004870093830751036,
            "refitEvery": 8,
        },
    },

    "Consistency": {
        "modelParameters": {
            "window_size": 1024,
            "n_trees": 175,
            "height": 8,
            "m_trees": 15,
            "weights": 0.5784309487067821,
        },
        "scoreMode": "movingAverage",
        "movingAverageWindow": 11,
        "dspot": {
            "calibrationWindow": 1050,
            "driftDepth": 155,
            "initialQuantile": 0.906476391723413,
            "risk": 0.0006616026263502567,
            "refitEvery": 11,
        },
    },

    "Generalization": {
        "modelParameters": {
            "window_size": 256,
            "n_trees": 125,
            "height": 15,
            "m_trees": 20,
            "weights": 0.6713413293192017,
        },
        "scoreMode": "movingAverage",
        "movingAverageWindow": 10,
        "dspot": {
            "calibrationWindow": 1200,
            "driftDepth": 150,
            "initialQuantile": 0.9485116180693848,
            "risk": 0.0003588919535806357,
            "refitEvery": 25,
        },
    },

    "Recurrence": {
        "modelParameters": {
            "window_size": 256,
            "n_trees": 150,
            "height": 15,
            "m_trees": 30,
            "weights": 0.9637706548224381,
        },
        "scoreMode": "movingAverage",
        "movingAverageWindow": 8,
        "dspot": {
            "calibrationWindow": 1300,
            "driftDepth": 35,
            "initialQuantile": 0.9175154020174382,
            "risk": 0.000591204169178966,
            "refitEvery": 3,
        },
    },
}


# Cada chave representa o dataset avaliado.
# A tupla indica quais perfis serão aplicados nesse dataset.
experimentSelection = {
    "Adaptation": (
        "Adaptation",
        "Consistency",
        "Generalization",
        "Recurrence",
    ),
    "Consistency": (
        "Adaptation",
        "Consistency",
        "Generalization",
        "Recurrence",
    ),
    "Generalization": (
        "Adaptation",
        "Consistency",
        "Generalization",
        "Recurrence",
    ),
    "Recurrence": (
        "Adaptation",
        "Consistency",
        "Generalization",
        "Recurrence",
    ),
}

In [7]:
FIXED_IMPUTER_NAME = "incrementalMean"
FIXED_NORMALIZER_NAME = "incrementalZScore"


unknownScenarios = sorted(
    set(experimentSelection)
    - set(scenarioDatasets)
)

unknownProfiles = sorted({
    profileName
    for selectedProfiles in experimentSelection.values()
    for profileName in selectedProfiles
    if profileName not in parameterProfiles
})

if unknownScenarios:
    raise KeyError(
        f"Cenários desconhecidos: {unknownScenarios}"
    )

if unknownProfiles:
    raise KeyError(
        f"Perfis desconhecidos: {unknownProfiles}"
    )


missingDatasets = [
    scenarioDatasets[scenarioName]
    for scenarioName in experimentSelection
    if not scenarioDatasets[scenarioName].exists()
]

if missingDatasets:
    missingText = "\n".join(
        str(path.resolve())
        for path in missingDatasets
    )

    raise FileNotFoundError(
        "Datasets não encontrados:\n"
        f"{missingText}"
    )


def prepareProfile(profileName):
    profile = parameterProfiles[profileName]

    executionModelParameters = dict(
        profile["modelParameters"]
    )

    scoreMode = profile["scoreMode"]

    if scoreMode == "raw":
        movingAverageWindow = pd.NA
        scoreWindowSizes = ()
        thresholdScoreSource = "raw"

    elif scoreMode == "movingAverage":
        movingAverageWindow = int(
            profile["movingAverageWindow"]
        )

        scoreWindowSizes = (
            movingAverageWindow,
        )

        thresholdScoreSource = (
            f"ma{movingAverageWindow}"
        )

    else:
        raise ValueError(
            f"scoreMode desconhecido no perfil "
            f"{profileName}: {scoreMode}"
        )

    dspotParameters = profile["dspot"]

    calibrationWindow = int(
        dspotParameters["calibrationWindow"]
    )

    driftDepth = int(
        dspotParameters["driftDepth"]
    )

    # A janela armazenada pelo Optuna inclui
    # driftDepth e calibrationSize.
    calibrationSize = (
        calibrationWindow - driftDepth
    )

    if calibrationSize < 20:
        raise ValueError(
            f"O perfil {profileName} possui somente "
            f"{calibrationSize} valores para calibrar "
            "a cauda do DSPOT."
        )

    if calibrationWindow > initialWarmupSize:
        raise ValueError(
            f"A calibração do perfil {profileName} "
            f"ultrapassa o warm-up de "
            f"{initialWarmupSize} instâncias."
        )

    dspotConfig = DspotConfig(
        driftDepth=driftDepth,
        calibrationSize=calibrationSize,
        initialQuantile=float(
            dspotParameters["initialQuantile"]
        ),
        risk=float(
            dspotParameters["risk"]
        ),
        refitEvery=int(
            dspotParameters["refitEvery"]
        ),
        optimizationStarts=int(
            defaults.DEFAULT_DSPOT_PARAMETERS[
                "optimizationStarts"
            ]
        ),
        tolerance=float(
            defaults.DEFAULT_DSPOT_PARAMETERS[
                "tolerance"
            ]
        ),
    )

    return {
        "profile": profile,
        "modelParameters": executionModelParameters,
        "scoreMode": scoreMode,
        "movingAverageWindow": movingAverageWindow,
        "scoreWindowSizes": scoreWindowSizes,
        "thresholdScoreSource": thresholdScoreSource,
        "calibrationWindow": calibrationWindow,
        "calibrationSize": calibrationSize,
        "driftDepth": driftDepth,
        "dspotConfig": dspotConfig,
    }


totalExecutions = sum(
    len(selectedProfiles)
    for selectedProfiles in experimentSelection.values()
)

print(
    f"Cenários selecionados: "
    f"{len(experimentSelection)}"
)
print(
    f"Perfis disponíveis: "
    f"{len(parameterProfiles)}"
)
print(
    f"Imputador fixo: "
    f"{FIXED_IMPUTER_NAME}"
)
print(
    f"Normalizador fixo: "
    f"{FIXED_NORMALIZER_NAME}"
)
print(
    f"Estratégia fixa: TrainAll"
)
print(
    f"Total de execuções: "
    f"{totalExecutions}"
)


resultDspotAll = {}
executionRecords = []
currentExecution = 0


for (
    datasetScenario,
    selectedProfiles,
) in experimentSelection.items():

    datasetPath = scenarioDatasets[
        datasetScenario
    ]

    datasetName = datasetPath.stem

    dataframe = pd.read_csv(
        datasetPath,
        low_memory=False,
    )

    print("\n" + "=" * 80)
    print(
        f"Cenário avaliado: "
        f"{datasetScenario}"
    )
    print(f"Dataset: {datasetName}")
    print(f"Arquivo: {datasetPath}")
    print(
        f"Instâncias originais: "
        f"{len(dataframe)}"
    )
    print("=" * 80)

    processor = DataStreamProcessor(
        logging=True,
        selected_features=selectedFeatures,
        removed_features=removedFeatures,
    )

    (
        stream,
        targetNames,
        featureNames,
        labelNames,
    ) = processor.create_stream(
        dataframe,
        target_label_col=targetColumn,
        binary_label=datasetProfile.binaryLabel,
    )

    resultDspotAll[datasetScenario] = {}


    for parameterProfileName in selectedProfiles:
        currentExecution += 1

        configuration = prepareProfile(
            parameterProfileName
        )

        executionModelParameters = (
            configuration["modelParameters"]
        )

        executionDspotConfig = (
            configuration["dspotConfig"]
        )

        thresholdScoreSource = (
            configuration[
                "thresholdScoreSource"
            ]
        )

        executionDescription = (
            f"[{currentExecution:02d}/"
            f"{totalExecutions:02d}] "
            f"Dataset={datasetScenario} | "
            f"Perfil={parameterProfileName} | "
            f"Imputer={FIXED_IMPUTER_NAME} | "
            f"Normalizer={FIXED_NORMALIZER_NAME} | "
            f"Score={thresholdScoreSource} | "
            "Strategy=TrainAll"
        )

        print(
            f"\nIniciando: "
            f"{executionDescription}"
        )

        recordBase = {
            "datasetScenario": datasetScenario,
            "dataset": datasetName,
            "parameterProfile": parameterProfileName,
            "aif_window_size": (
                executionModelParameters[
                    "window_size"
                ]
            ),
            "aif_n_trees": (
                executionModelParameters[
                    "n_trees"
                ]
            ),
            "aif_height": (
                executionModelParameters[
                    "height"
                ]
            ),
            "aif_m_trees": (
                executionModelParameters[
                    "m_trees"
                ]
            ),
            "aif_weights": (
                executionModelParameters[
                    "weights"
                ]
            ),
            "imputer": FIXED_IMPUTER_NAME,
            "normalizer": FIXED_NORMALIZER_NAME,
            "scoreMode": (
                configuration["scoreMode"]
            ),
            "movingAverageWindow": (
                configuration[
                    "movingAverageWindow"
                ]
            ),
            "thresholdScoreSource": (
                thresholdScoreSource
            ),
            "calibrationWindow": (
                configuration[
                    "calibrationWindow"
                ]
            ),
            "calibrationSize": (
                configuration[
                    "calibrationSize"
                ]
            ),
            "driftDepth": (
                configuration["driftDepth"]
            ),
            "initialQuantile": (
                executionDspotConfig
                .initialQuantile
            ),
            "risk": (
                executionDspotConfig.risk
            ),
            "refitEvery": (
                executionDspotConfig
                .refitEvery
            ),
            "trainingStrategy": "all",
        }

        try:
            pipeline = TrainingPipeline(
                stream=stream,
                datasetName=datasetName,
                modelCode=modelCode,
                threshold=DspotThreshold(
                    executionDspotConfig
                ),
                labelNames=labelNames,
                modelParameters=(
                    executionModelParameters
                ),
                imputer=imputerFactory(),
                normalizer=normalizerFactory(),
                trainingStrategy=(
                    TrainAllStrategy()
                ),
                scoreWindowSizes=(
                    configuration[
                        "scoreWindowSizes"
                    ]
                ),
                metricsWindowSize=(
                    metricsWindowSize
                ),
                outputPath=outputPath,
                normalClassIndex=(
                    defaults
                    .DEFAULT_NORMAL_CLASS_INDEX
                ),
                seed=seed,
                generatePlots=True,
                initialWarmupSize=(
                    initialWarmupSize
                ),
                thresholdScoreSource=(
                    thresholdScoreSource
                ),
            )

            executionResult = pipeline.run()

            streamMetrics = (
                executionResult[
                    "streamMetricsFrame"
                ]
                .iloc[0]
            )

            resultDspotAll[
                datasetScenario
            ][
                parameterProfileName
            ] = {
                "parameters": (
                    configuration["profile"]
                ),
                "runDirectory": (
                    executionResult[
                        "runDirectory"
                    ]
                ),
                "streamMetricsPath": (
                    executionResult[
                        "streamMetricsPath"
                    ]
                ),
            }

            executionRecords.append({
                **recordBase,
                "instances": int(
                    streamMetrics[
                        "totalInstances"
                    ]
                ),
                "evaluatedInstances": int(
                    streamMetrics[
                        "evaluatedInstances"
                    ]
                ),
                "attackRatioPercent": float(
                    streamMetrics[
                        "attackRatioPercent"
                    ]
                ),
                "precision": float(
                    streamMetrics["precision"]
                ),
                "recall": float(
                    streamMetrics["recall"]
                ),
                "f1": float(
                    streamMetrics["f1"]
                ),
                "fp": int(
                    streamMetrics["fp"]
                ),
                "fn": int(
                    streamMetrics["fn"]
                ),
                "status": "Concluída",
                "error": "",
                "runDirectory": (
                    executionResult[
                        "runDirectory"
                    ]
                ),
                "resultPath": (
                    executionResult[
                        "streamMetricsPath"
                    ]
                ),
            })

            print(
                f"Concluída: "
                f"{executionDescription} | "
                f"F1={streamMetrics['f1']:.6f}"
            )

        except Exception as error:
            resultDspotAll[
                datasetScenario
            ][
                parameterProfileName
            ] = None

            executionRecords.append({
                **recordBase,
                "instances": len(dataframe),
                "evaluatedInstances": pd.NA,
                "attackRatioPercent": pd.NA,
                "precision": pd.NA,
                "recall": pd.NA,
                "f1": pd.NA,
                "fp": pd.NA,
                "fn": pd.NA,
                "status": "Erro",
                "error": str(error),
                "runDirectory": "",
                "resultPath": "",
            })

            print(
                f"Erro: "
                f"{executionDescription}"
            )
            print(
                f"Motivo: {error}"
            )


executionSummary = pd.DataFrame(
    executionRecords
)

completedExecutions = int(
    executionSummary["status"]
    .eq("Concluída")
    .sum()
)

failedExecutions = int(
    executionSummary["status"]
    .eq("Erro")
    .sum()
)

print("\nResumo final")
print(
    f"Execuções concluídas: "
    f"{completedExecutions}"
)
print(
    f"Execuções com erro: "
    f"{failedExecutions}"
)

display(executionSummary)

Cenários selecionados: 4
Perfis disponíveis: 4
Imputador fixo: incrementalMean
Normalizador fixo: incrementalZScore
Estratégia fixa: TrainAll
Total de execuções: 16

================================================================================
Cenário avaliado: Adaptation
Dataset: Adaptação_200
Arquivo: data\15k\Adaptação\Adaptação_200.csv
Instâncias originais: 15600
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 15600 instâncias e 33 features.
Treinamento: binário.
Rótulos originais preservados: 3 classes.
Valores ausentes preservados para imputação online: 0.

Iniciando: [01/16] Dataset=Adaptation | Perfil=Adaptation | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma10 | Strategy=TrainAll
Concluída: [01/16] Dataset=Adaptation | Perfil=Adaptation | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma10 | Strategy=TrainAll | F1=0.751817

Iniciando: [02/16] Dataset=Adaptation | Perfil=Consistency | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma11 | Strategy=TrainAll
Concluída: [02/16] Dataset=Adaptation | Perfil=Consistency | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma11 | Strategy=TrainAll | F1=0.748971

Iniciando: [03/16] Dataset=Adaptation | Perfil=Generalization | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma10 | Strategy=TrainAll
Concluída: [03/16] Dataset=Adaptation | Perfil=Generalization | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma10 | Strategy=TrainAll | F1=0.750515

Iniciando: [04/16] Dataset=Adaptation | Perfil=Recurrence | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma8 | Strategy=TrainAll
Concluída: [04/16] Dataset=Adaptation | Perfil=Recurrence | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma8 | Strategy=TrainAll | F1=0.752083

================================================================================
Cenário avaliado: Consistency
Dataset: Consistência_200
Arquivo: data\15k\Consistência\Consistência_200.csv
Instâncias originais: 15600
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 15600 instâncias e 33 features.
Treinamento: binário.
Rótulos originais preservados: 2 classes.
Valores ausentes preservados para imputação online: 0.

Iniciando: [05/16] Dataset=Consistency | Perfil=Adaptation | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma10 | Strategy=TrainAll
Concluída: [05/16] Dataset=Consistency | Perfil=Adaptation | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma10 | Strategy=TrainAll | F1=0.725749

Iniciando: [06/16] Dataset=Consistency | Perfil=Consistency | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma11 | Strategy=TrainAll
Concluída: [06/16] Dataset=Consistency | Perfil=Consistency | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma11 | Strategy=TrainAll | F1=0.923077

Iniciando: [07/16] Dataset=Consistency | Perfil=Generalization | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma10 | Strategy=TrainAll
Concluída: [07/16] Dataset=Consistency | Perfil=Generalization | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma10 | Strategy=TrainAll | F1=0.922619

Iniciando: [08/16] Dataset=Consistency | Perfil=Recurrence | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma8 | Strategy=TrainAll
Concluída: [08/16] Dataset=Consistency | Perfil=Recurrence | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma8 | Strategy=TrainAll | F1=0.769409

================================================================================
Cenário avaliado: Generalization
Dataset: Generalização_200
Arquivo: data\15k\Generalização\Generalização_200.csv
Instâncias originais: 15600
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 15600 instâncias e 33 features.
Treinamento: binário.
Rótulos originais preservados: 3 classes.
Valores ausentes preservados para imputação online: 0.

Iniciando: [09/16] Dataset=Generalization | Perfil=Adaptation | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma10 | Strategy=TrainAll
Concluída: [09/16] Dataset=Generalization | Perfil=Adaptation | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma10 | Strategy=TrainAll | F1=0.782077

Iniciando: [10/16] Dataset=Generalization | Perfil=Consistency | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma11 | Strategy=TrainAll
Concluída: [10/16] Dataset=Generalization | Perfil=Consistency | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma11 | Strategy=TrainAll | F1=0.955479

Iniciando: [11/16] Dataset=Generalization | Perfil=Generalization | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma10 | Strategy=TrainAll
Concluída: [11/16] Dataset=Generalization | Perfil=Generalization | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma10 | Strategy=TrainAll | F1=0.957045

Iniciando: [12/16] Dataset=Generalization | Perfil=Recurrence | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma8 | Strategy=TrainAll
Concluída: [12/16] Dataset=Generalization | Perfil=Recurrence | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma8 | Strategy=TrainAll | F1=0.739726

================================================================================
Cenário avaliado: Recurrence
Dataset: Recorrência_200
Arquivo: data\15k\Recorrência\Recorrência_200.csv
Instâncias originais: 15600
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 15600 instâncias e 33 features.
Treinamento: binário.
Rótulos originais preservados: 4 classes.
Valores ausentes preservados para imputação online: 0.

Iniciando: [13/16] Dataset=Recurrence | Perfil=Adaptation | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma10 | Strategy=TrainAll
Concluída: [13/16] Dataset=Recurrence | Perfil=Adaptation | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma10 | Strategy=TrainAll | F1=0.732275

Iniciando: [14/16] Dataset=Recurrence | Perfil=Consistency | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma11 | Strategy=TrainAll
Concluída: [14/16] Dataset=Recurrence | Perfil=Consistency | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma11 | Strategy=TrainAll | F1=0.744856

Iniciando: [15/16] Dataset=Recurrence | Perfil=Generalization | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma10 | Strategy=TrainAll
Concluída: [15/16] Dataset=Recurrence | Perfil=Generalization | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma10 | Strategy=TrainAll | F1=0.746639

Iniciando: [16/16] Dataset=Recurrence | Perfil=Recurrence | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma8 | Strategy=TrainAll
Concluída: [16/16] Dataset=Recurrence | Perfil=Recurrence | Imputer=incrementalMean | Normalizer=incrementalZScore | Score=ma8 | Strategy=TrainAll | F1=0.749220

Resumo final
Execuções concluídas: 16
Execuções com erro: 0

,datasetScenario,dataset,parameterProfile,aif_window_size,aif_n_trees,aif_height,aif_m_trees,aif_weights,imputer,normalizer,...,attackRatioPercent,precision,recall,f1,fp,fn,status,error,runDirectory,resultPath
0,Adaptation,Adaptação_200,Adaptation,512,200,13,15,0.313250,incrementalMean,incrementalZScore,...,4.191176,0.921120,0.635088,0.751817,31,208,Concluída,,output\AIF\Adaptation_200\001-ALL-DSPOT-MA10-MEAN,output\AIF\Adaptation_200\001-ALL-DSPOT-MA10-M...
1,Adaptation,Adaptação_200,Consistency,1024,175,8,15,0.578431,incrementalMean,incrementalZScore,...,4.191176,0.905473,0.638596,0.748971,38,206,Concluída,,output\AIF\Adaptation_200\002-ALL-DSPOT-MA11-MEAN,output\AIF\Adaptation_200\002-ALL-DSPOT-MA11-M...
2,Adaptation,Adaptação_200,Generalization,256,125,15,20,0.671341,incrementalMean,incrementalZScore,...,4.191176,0.910000,0.638596,0.750515,36,206,Concluída,,output\AIF\Adaptation_200\003-ALL-DSPOT-MA10-MEAN,output\AIF\Adaptation_200\003-ALL-DSPOT-MA10-M...
3,Adaptation,Adaptação_200,Recurrence,256,150,15,30,0.963771,incrementalMean,incrementalZScore,...,4.191176,0.925641,0.633333,0.752083,29,209,Concluída,,output\AIF\Adaptation_200\004-ALL-DSPOT-MA8-MEAN,output\AIF\Adaptation_200\004-ALL-DSPOT-MA8-ME...
4,Consistency,Consistência_200,Adaptation,512,200,13,15,0.313250,incrementalMean,incrementalZScore,...,3.705882,0.915408,0.601190,0.725749,28,201,Concluída,,output\AIF\Consistency_200\001-ALL-DSPOT-MA10-...,output\AIF\Consistency_200\001-ALL-DSPOT-MA10-...
5,Consistency,Consistência_200,Consistency,1024,175,8,15,0.578431,incrementalMean,incrementalZScore,...,3.705882,0.917647,0.928571,0.923077,42,36,Concluída,,output\AIF\Consistency_200\002-ALL-DSPOT-MA11-...,output\AIF\Consistency_200\002-ALL-DSPOT-MA11-...
6,Consistency,Consistência_200,Generalization,256,125,15,20,0.671341,incrementalMean,incrementalZScore,...,3.705882,0.922619,0.922619,0.922619,39,39,Concluída,,output\AIF\Consistency_200\003-ALL-DSPOT-MA10-...,output\AIF\Consistency_200\003-ALL-DSPOT-MA10-...
7,Consistency,Consistência_200,Recurrence,256,150,15,30,0.963771,incrementalMean,incrementalZScore,...,3.705882,0.924791,0.658730,0.769409,27,172,Concluída,,output\AIF\Consistency_200\004-ALL-DSPOT-MA8-MEAN,output\AIF\Consistency_200\004-ALL-DSPOT-MA8-M...
8,Generalization,Generalização_200,Adaptation,512,200,13,15,0.313250,incrementalMean,incrementalZScore,...,4.205882,0.936585,0.671329,0.782077,26,188,Concluída,,output\AIF\Generalization_200\001-ALL-DSPOT-MA...,output\AIF\Generalization_200\001-ALL-DSPOT-MA...
9,Generalization,Generalização_200,Consistency,1024,175,8,15,0.578431,incrementalMean,incrementalZScore,...,4.205882,0.936242,0.975524,0.955479,38,14,Concluída,,output\AIF\Generalization_200\002-ALL-DSPOT-MA...,output\AIF\Generalization_200\002-ALL-DSPOT-MA...
10,Generalization,Generalização_200,Generalization,256,125,15,20,0.671341,incrementalMean,incrementalZScore,...,4.205882,0.940878,0.973776,0.957045,35,15,Concluída,,output\AIF\Generalization_200\003-ALL-DSPOT-MA...,output\AIF\Generalization_200\003-ALL-DSPOT-MA...
11,Generalization,Generalização_200,Recurrence,256,150,15,30,0.963771,incrementalMean,incrementalZScore,...,4.205882,0.931034,0.613636,0.739726,26,221,Concluída,,output\AIF\Generalization_200\004-ALL-DSPOT-MA...,output\AIF\Generalization_200\004-ALL-DSPOT-MA...
12,Recurrence,Recorrência_200,Adaptation,512,200,13,15,0.313250,incrementalMean,incrementalZScore,...,4.227941,0.935135,0.601739,0.732275,24,229,Concluída,,output\AIF\Recurrence_200\001-ALL-DSPOT-MA10-MEAN,output\AIF\Recurrence_200\001-ALL-DSPOT-MA10-M...
13,Recurrence,Recorrência_200,Consistency,1024,175,8,15,0.578431,incrementalMean,incrementalZScore,...,4.227941,0.911839,0.629565,0.744856,35,213,Concluída,,output\AIF\Recurrence_200\002-ALL-DSPOT-MA11-MEAN,output\AIF\Recurrence_200\002-ALL-DSPOT-MA11-M...
14,Recurrence,Recorrência_200,Generalization,256,125,15,20,0.671341,incrementalMean,incrementalZScore,...,4.227941,0.920918,0.627826,0.746639,31,214,Concluída,,output\AIF\Recurrence_200\003-ALL-DSPOT-MA10-MEAN,output\AIF\Recurrence_200\003-ALL-DSPOT-MA10-M...
15,Recurrence,Recorrência_200,Recurrence,256,150,15,30,0.963771,incrementalMean,incrementalZScore,...,4.227941,0.932642,0.626087,0.749220,26,215,Concluída,,output\AIF\Recurrence_200\004-ALL-DSPOT-MA8-MEAN,output\AIF\Recurrence_200\004-ALL-DSPOT-MA8-ME...

#### Treinando novos cenários com parâmetros selecionados como estáveis

In [8]:
BEST_PARAMETERS = {
    "aif": {
        "window_size": 256,
        "n_trees": 125,
        "height": 15,
        "m_trees": 20,
        "weights": 0.6713413293192017,
    },

    "score": {
        "mode": "movingAverage",
        "movingAverageWindow": 10,
    },

    "dspot": {
        "calibrationWindow": 1200,
        "driftDepth": 150,
        "initialQuantile": 0.9485116180693848,
        "risk": 0.0003588919535806357,
        "refitEvery": 25,
    },

    "execution": {
        "initialWarmupSize": 2000,
        "metricsWindowSize": 100,
        "seed": 42,
        "generatePlots": True,
    },
}

In [10]:
dataRoot = Path("data\\new")
outputRoot = Path("output")

datasetFileNames = (
    "DNS.csv",
    "LDAP.csv",
    "MSSQL.csv",
    "NetBIOS.csv",
    "NTP.csv",
    "SNMP.csv",
    "SSDP.csv",
    "Syn_SNMP.csv",
    "Syn_TFTP.csv",
    "Syn_UDP-lag.csv",
    "Syn.csv",
    "TFTP.csv",
    "UDP-lag.csv",
    "UDP.csv",
)

datasetPaths = [
    dataRoot / fileName
    for fileName in datasetFileNames
]


missingDatasets = [
    datasetPath
    for datasetPath in datasetPaths
    if not datasetPath.exists()
]

if missingDatasets:
    missingText = "\n".join(
        str(datasetPath.resolve())
        for datasetPath in missingDatasets
    )

    raise FileNotFoundError(
        "Os seguintes datasets não foram encontrados:\n"
        f"{missingText}"
    )


aifParameters = dict(
    BEST_PARAMETERS["aif"]
)

scoreParameters = dict(
    BEST_PARAMETERS["score"]
)

dspotParameters = dict(
    BEST_PARAMETERS["dspot"]
)

executionParameters = dict(
    BEST_PARAMETERS["execution"]
)


scoreMode = scoreParameters["mode"]

if scoreMode == "raw":
    movingAverageWindow = pd.NA
    scoreWindowSizes = ()
    thresholdScoreSource = "raw"

elif scoreMode == "movingAverage":
    movingAverageWindow = int(
        scoreParameters[
            "movingAverageWindow"
        ]
    )

    scoreWindowSizes = (
        movingAverageWindow,
    )

    thresholdScoreSource = (
        f"ma{movingAverageWindow}"
    )

else:
    raise ValueError(
        "O modo do score deve ser "
        "'raw' ou 'movingAverage'."
    )


calibrationWindow = int(
    dspotParameters[
        "calibrationWindow"
    ]
)

driftDepth = int(
    dspotParameters[
        "driftDepth"
    ]
)

calibrationSize = (
    calibrationWindow - driftDepth
)

initialWarmupSize = int(
    executionParameters[
        "initialWarmupSize"
    ]
)

if calibrationSize < 20:
    raise ValueError(
        "A diferença entre calibrationWindow "
        "e driftDepth deve preservar pelo menos "
        "20 valores para a calibração da cauda."
    )

if calibrationWindow > initialWarmupSize:
    raise ValueError(
        "A janela de calibração do DSPOT "
        "não pode ultrapassar o warm-up."
    )


dspotConfig = DspotConfig(
    driftDepth=driftDepth,
    calibrationSize=calibrationSize,
    initialQuantile=float(
        dspotParameters[
            "initialQuantile"
        ]
    ),
    risk=float(
        dspotParameters[
            "risk"
        ]
    ),
    refitEvery=int(
        dspotParameters[
            "refitEvery"
        ]
    ),
    optimizationStarts=int(
        defaults.DEFAULT_DSPOT_PARAMETERS[
            "optimizationStarts"
        ]
    ),
    tolerance=float(
        defaults.DEFAULT_DSPOT_PARAMETERS[
            "tolerance"
        ]
    ),
)


print(
    f"Datasets encontrados: "
    f"{len(datasetPaths)}"
)
print(
    "Imputador fixo: "
    "IncrementalMeanImputer"
)
print(
    "Normalizador fixo: "
    "IncrementalZScoreNormalizer"
)
print(
    "Estratégia fixa: TrainAll"
)
print(
    f"Score enviado ao DSPOT: "
    f"{thresholdScoreSource}"
)
print(
    f"Total de execuções: "
    f"{len(datasetPaths)}"
)


newScenarioResults = {}
executionRecords = []


for executionIndex, datasetPath in enumerate(
    datasetPaths,
    start=1,
):
    datasetName = datasetPath.stem

    print("\n" + "=" * 80)
    print(
        f"[{executionIndex:02d}/"
        f"{len(datasetPaths):02d}] "
        f"Dataset: {datasetName}"
    )
    print(f"Arquivo: {datasetPath}")
    print("=" * 80)

    dataframe = pd.read_csv(
        datasetPath,
        low_memory=False,
    )

    processor = DataStreamProcessor(
        logging=True,
        selected_features=None,
        removed_features=removedFeatures,
    )

    (
        stream,
        targetNames,
        featureNames,
        labelNames,
    ) = processor.create_stream(
        dataframe,
        target_label_col=targetColumn,
        binary_label=(
            datasetProfile.binaryLabel
        ),
    )

    try:
        pipeline = TrainingPipeline(
            stream=stream,
            datasetName=datasetName,
            modelCode="AIF",
            threshold=DspotThreshold(
                DspotConfig(
                    driftDepth=(
                        dspotConfig.driftDepth
                    ),
                    calibrationSize=(
                        dspotConfig.calibrationSize
                    ),
                    initialQuantile=(
                        dspotConfig.initialQuantile
                    ),
                    risk=dspotConfig.risk,
                    refitEvery=(
                        dspotConfig.refitEvery
                    ),
                    optimizationStarts=(
                        dspotConfig
                        .optimizationStarts
                    ),
                    tolerance=(
                        dspotConfig.tolerance
                    ),
                )
            ),
            labelNames=labelNames,
            modelParameters=dict(
                aifParameters
            ),
            imputer=(
                IncrementalMeanImputer()
            ),
            normalizer=(
                IncrementalZScoreNormalizer(
                    **defaults
                    .DEFAULT_NORMALIZER_PARAMETERS
                )
            ),
            trainingStrategy=(
                TrainAllStrategy()
            ),
            scoreWindowSizes=(
                scoreWindowSizes
            ),
            metricsWindowSize=int(
                executionParameters[
                    "metricsWindowSize"
                ]
            ),
            outputPath=outputRoot,
            normalClassIndex=(
                defaults
                .DEFAULT_NORMAL_CLASS_INDEX
            ),
            seed=int(
                executionParameters["seed"]
            ),
            generatePlots=bool(
                executionParameters[
                    "generatePlots"
                ]
            ),
            initialWarmupSize=(
                initialWarmupSize
            ),
            thresholdScoreSource=(
                thresholdScoreSource
            ),
        )

        executionResult = pipeline.run()

        streamMetrics = (
            executionResult[
                "streamMetricsFrame"
            ]
            .iloc[0]
        )

        newScenarioResults[
            datasetName
        ] = {
            "runDirectory": (
                executionResult[
                    "runDirectory"
                ]
            ),
            "streamMetricsPath": (
                executionResult[
                    "streamMetricsPath"
                ]
            ),
        }

        executionRecords.append({
            "dataset": datasetName,
            "instances": int(
                streamMetrics[
                    "totalInstances"
                ]
            ),
            "evaluatedInstances": int(
                streamMetrics[
                    "evaluatedInstances"
                ]
            ),
            "attackRatioPercent": float(
                streamMetrics[
                    "attackRatioPercent"
                ]
            ),
            "precision": float(
                streamMetrics[
                    "precision"
                ]
            ),
            "recall": float(
                streamMetrics["recall"]
            ),
            "f1": float(
                streamMetrics["f1"]
            ),
            "fp": int(
                streamMetrics["fp"]
            ),
            "fn": int(
                streamMetrics["fn"]
            ),
            "status": "Concluída",
            "error": "",
            "runDirectory": (
                executionResult[
                    "runDirectory"
                ]
            ),
            "resultPath": (
                executionResult[
                    "streamMetricsPath"
                ]
            ),
        })

        print(
            f"Concluído: {datasetName} | "
            f"F1={streamMetrics['f1']:.6f}"
        )
        print(
            "Resultados salvos em: "
            f"{executionResult['runDirectory']}"
        )

    except Exception as error:
        newScenarioResults[
            datasetName
        ] = None

        executionRecords.append({
            "dataset": datasetName,
            "instances": len(dataframe),
            "evaluatedInstances": pd.NA,
            "attackRatioPercent": pd.NA,
            "precision": pd.NA,
            "recall": pd.NA,
            "f1": pd.NA,
            "fp": pd.NA,
            "fn": pd.NA,
            "status": "Erro",
            "error": str(error),
            "runDirectory": "",
            "resultPath": "",
        })

        print(
            f"Erro no dataset "
            f"{datasetName}: {error}"
        )


executionSummary = pd.DataFrame(
    executionRecords
)

completedExecutions = int(
    executionSummary["status"]
    .eq("Concluída")
    .sum()
)

failedExecutions = int(
    executionSummary["status"]
    .eq("Erro")
    .sum()
)

print("\nResumo final")
print(
    f"Execuções concluídas: "
    f"{completedExecutions}"
)
print(
    f"Execuções com erro: "
    f"{failedExecutions}"
)

display(executionSummary)

Datasets encontrados: 14
Imputador fixo: IncrementalMeanImputer
Normalizador fixo: IncrementalZScoreNormalizer
Estratégia fixa: TrainAll
Score enviado ao DSPOT: ma10
Total de execuções: 14

================================================================================
[01/14] Dataset: DNS
Arquivo: data\new\DNS.csv
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 13200 instâncias e 83 features.
Treinamento: binário.
Rótulos originais preservados: 2 classes.
Valores ausentes preservados para imputação online: 26620.
Concluído: DNS | F1=0.948905
Resultados salvos em: output\AIF\DNS\002-ALL-DSPOT-MA10-MEAN

================================================================================
[02/14] Dataset: LDAP
Arquivo: data\new\LDAP.csv
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 13200 instâncias e 83 features.
Treinamento: binário.
Rótulos originais preservados: 2 classes.
Valores ausentes preservados para imputação online: 26612.
Concluído: LDAP | F1=0.949153
Resultados salvos em: output\AIF\LDAP\002-ALL-DSPOT-MA10-MEAN

================================================================================
[03/14] Dataset: MSSQL
Arquivo: data\new\MSSQL.csv
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 13200 instâncias e 83 features.
Treinamento: binário.
Rótulos originais preservados: 2 classes.
Valores ausentes preservados para imputação online: 26608.
Concluído: MSSQL | F1=0.724458
Resultados salvos em: output\AIF\MSSQL\002-ALL-DSPOT-MA10-MEAN

================================================================================
[04/14] Dataset: NetBIOS
Arquivo: data\new\NetBIOS.csv
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 13200 instâncias e 83 features.
Treinamento: binário.
Rótulos originais preservados: 2 classes.
Valores ausentes preservados para imputação online: 26626.
Concluído: NetBIOS | F1=0.047847
Resultados salvos em: output\AIF\NetBIOS\002-ALL-DSPOT-MA10-MEAN

================================================================================
[05/14] Dataset: NTP
Arquivo: data\new\NTP.csv
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 13200 instâncias e 83 features.
Treinamento: binário.
Rótulos originais preservados: 2 classes.
Valores ausentes preservados para imputação online: 26606.
Concluído: NTP | F1=0.864865
Resultados salvos em: output\AIF\NTP\002-ALL-DSPOT-MA10-MEAN

================================================================================
[06/14] Dataset: SNMP
Arquivo: data\new\SNMP.csv
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 13200 instâncias e 83 features.
Treinamento: binário.
Rótulos originais preservados: 2 classes.
Valores ausentes preservados para imputação online: 26614.
Concluído: SNMP | F1=0.000000
Resultados salvos em: output\AIF\SNMP\002-ALL-DSPOT-MA10-MEAN

================================================================================
[07/14] Dataset: SSDP
Arquivo: data\new\SSDP.csv
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 13200 instâncias e 83 features.
Treinamento: binário.
Rótulos originais preservados: 2 classes.
Valores ausentes preservados para imputação online: 26610.
Concluído: SSDP | F1=0.468401
Resultados salvos em: output\AIF\SSDP\002-ALL-DSPOT-MA10-MEAN

================================================================================
[08/14] Dataset: Syn_SNMP
Arquivo: data\new\Syn_SNMP.csv
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 13600 instâncias e 83 features.
Treinamento: binário.
Rótulos originais preservados: 3 classes.
Valores ausentes preservados para imputação online: 27458.
Concluído: Syn_SNMP | F1=0.029557
Resultados salvos em: output\AIF\Syn_SNMP\002-ALL-DSPOT-MA10-MEAN

================================================================================
[09/14] Dataset: Syn_TFTP
Arquivo: data\new\Syn_TFTP.csv
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 13600 instâncias e 83 features.
Treinamento: binário.
Rótulos originais preservados: 3 classes.
Valores ausentes preservados para imputação online: 27522.
Concluído: Syn_TFTP | F1=0.032680
Resultados salvos em: output\AIF\Syn_TFTP\002-ALL-DSPOT-MA10-MEAN

================================================================================
[10/14] Dataset: Syn_UDP-lag
Arquivo: data\new\Syn_UDP-lag.csv
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 13600 instâncias e 83 features.
Treinamento: binário.
Rótulos originais preservados: 3 classes.
Valores ausentes preservados para imputação online: 27464.
Concluído: Syn_UDP-lag | F1=0.032787
Resultados salvos em: output\AIF\Syn_UDP_lag\002-ALL-DSPOT-MA10-MEAN

================================================================================
[11/14] Dataset: Syn
Arquivo: data\new\Syn.csv
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 13200 instâncias e 83 features.
Treinamento: binário.
Rótulos originais preservados: 2 classes.
Valores ausentes preservados para imputação online: 26634.
Concluído: Syn | F1=0.000000
Resultados salvos em: output\AIF\Syn\002-ALL-DSPOT-MA10-MEAN

================================================================================
[12/14] Dataset: TFTP
Arquivo: data\new\TFTP.csv
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 13200 instâncias e 83 features.
Treinamento: binário.
Rótulos originais preservados: 2 classes.
Valores ausentes preservados para imputação online: 26644.
Concluído: TFTP | F1=0.000000
Resultados salvos em: output\AIF\TFTP\002-ALL-DSPOT-MA10-MEAN

================================================================================
[13/14] Dataset: UDP-lag
Arquivo: data\new\UDP-lag.csv
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 13200 instâncias e 83 features.
Treinamento: binário.
Rótulos originais preservados: 2 classes.
Valores ausentes preservados para imputação online: 26614.
Concluído: UDP-lag | F1=0.075829
Resultados salvos em: output\AIF\UDP_lag\002-ALL-DSPOT-MA10-MEAN

================================================================================
[14/14] Dataset: UDP
Arquivo: data\new\UDP.csv
================================================================================
Linhas removidas por rótulo ausente ou vazio: 0.
Stream criada com 13200 instâncias e 83 features.
Treinamento: binário.
Rótulos originais preservados: 2 classes.
Valores ausentes preservados para imputação online: 26612.
Concluído: UDP | F1=0.111111
Resultados salvos em: output\AIF\UDP\002-ALL-DSPOT-MA10-MEAN

Resumo final
Execuções concluídas: 14
Execuções com erro: 0

,dataset,instances,evaluatedInstances,attackRatioPercent,precision,recall,f1,fp,fn,status,error,runDirectory,resultPath
0,DNS,13200,11200,1.785714,0.924171,0.975000,0.948905,16,5,Concluída,,output\AIF\DNS\002-ALL-DSPOT-MA10-MEAN,output\AIF\DNS\002-ALL-DSPOT-MA10-MEAN\stream_...
1,LDAP,13200,11200,1.785714,0.920188,0.980000,0.949153,17,4,Concluída,,output\AIF\LDAP\002-ALL-DSPOT-MA10-MEAN,output\AIF\LDAP\002-ALL-DSPOT-MA10-MEAN\stream...
2,MSSQL,13200,11200,1.785714,0.951220,0.585000,0.724458,6,83,Concluída,,output\AIF\MSSQL\002-ALL-DSPOT-MA10-MEAN,output\AIF\MSSQL\002-ALL-DSPOT-MA10-MEAN\strea...
3,NetBIOS,13200,11200,1.785714,0.555556,0.025000,0.047847,4,195,Concluída,,output\AIF\NetBIOS\002-ALL-DSPOT-MA10-MEAN,output\AIF\NetBIOS\002-ALL-DSPOT-MA10-MEAN\str...
4,NTP,13200,11200,1.785714,0.941176,0.800000,0.864865,10,40,Concluída,,output\AIF\NTP\002-ALL-DSPOT-MA10-MEAN,output\AIF\NTP\002-ALL-DSPOT-MA10-MEAN\stream_...
5,SNMP,13200,11200,1.785714,0.000000,0.000000,0.000000,5,200,Concluída,,output\AIF\SNMP\002-ALL-DSPOT-MA10-MEAN,output\AIF\SNMP\002-ALL-DSPOT-MA10-MEAN\stream...
6,SSDP,13200,11200,1.785714,0.913043,0.315000,0.468401,6,137,Concluída,,output\AIF\SSDP\002-ALL-DSPOT-MA10-MEAN,output\AIF\SSDP\002-ALL-DSPOT-MA10-MEAN\stream...
7,Syn_SNMP,13600,11600,5.172414,1.000000,0.015000,0.029557,0,591,Concluída,,output\AIF\Syn_SNMP\002-ALL-DSPOT-MA10-MEAN,output\AIF\Syn_SNMP\002-ALL-DSPOT-MA10-MEAN\st...
8,Syn_TFTP,13600,11600,5.172414,0.833333,0.016667,0.032680,2,590,Concluída,,output\AIF\Syn_TFTP\002-ALL-DSPOT-MA10-MEAN,output\AIF\Syn_TFTP\002-ALL-DSPOT-MA10-MEAN\st...
9,Syn_UDP-lag,13600,11600,5.172414,1.000000,0.016667,0.032787,0,590,Concluída,,output\AIF\Syn_UDP_lag\002-ALL-DSPOT-MA10-MEAN,output\AIF\Syn_UDP_lag\002-ALL-DSPOT-MA10-MEAN...
10,Syn,13200,11200,1.785714,0.000000,0.000000,0.000000,5,200,Concluída,,output\AIF\Syn\002-ALL-DSPOT-MA10-MEAN,output\AIF\Syn\002-ALL-DSPOT-MA10-MEAN\stream_...
11,TFTP,13200,11200,1.785714,0.000000,0.000000,0.000000,5,200,Concluída,,output\AIF\TFTP\002-ALL-DSPOT-MA10-MEAN,output\AIF\TFTP\002-ALL-DSPOT-MA10-MEAN\stream...
12,UDP-lag,13200,11200,1.785714,0.727273,0.040000,0.075829,3,192,Concluída,,output\AIF\UDP_lag\002-ALL-DSPOT-MA10-MEAN,output\AIF\UDP_lag\002-ALL-DSPOT-MA10-MEAN\str...
13,UDP,13200,11200,1.785714,0.750000,0.060000,0.111111,4,188,Concluída,,output\AIF\UDP\002-ALL-DSPOT-MA10-MEAN,output\AIF\UDP\002-ALL-DSPOT-MA10-MEAN\stream_...