# Binary Classification

Incremental supervised training with the same binary target used by anomaly detection: `BENIGN=0` and `ATTACK=1`.

In [1]:
from src.Classification import ClassifierRegistry
from src.Experiment import ExperimentRunner

In [2]:
selectedFeatures = [
    "Flow_Duration",
    "Total_Fwd_Packets",
    "Total_Backward_Packets",
    "Total_Length_of_Fwd_Packets",
    "Fwd_Packet_Length_Max",
    "Fwd_Packet_Length_Min",
    "Fwd_Packet_Length_Mean",
    "Fwd_Packet_Length_Std",
    "Bwd_Packet_Length_Mean",
    "Flow_Bytes_s",
    "Flow_Packets_s",
    "Flow_IAT_Mean",
    "Flow_IAT_Std",
    "Flow_IAT_Max",
    "Fwd_IAT_Total",
    "Fwd_IAT_Std",
    "Fwd_IAT_Max",
    "Fwd_IAT_Min",
    "Fwd_Header_Length",
    "Bwd_Header_Length",
    "Fwd_Packets_s",
    "Bwd_Packets_s",
    "Min_Packet_Length",
    "Max_Packet_Length",
    "Packet_Length_Mean",
    "Packet_Length_Std",
    "Packet_Length_Variance",
    "ACK_Flag_Count",
    "CWE_Flag_Count",
    "Down_Up_Ratio",
    "Average_Packet_Size",
    "Avg_Fwd_Segment_Size",
    "Subflow_Fwd_Packets",
    "Subflow_Fwd_Bytes",
    "Subflow_Bwd_Packets",
    "Init_Win_bytes_forward",
    "Init_Win_bytes_backward",
    "act_data_pkt_fwd",
    "min_seg_size_forward"
]

# experimentName = "CICDDoS2019_Classification_1s"

# datasets = {
#     "Consistency_1s": {
#         "path": r"data/scenario/Consistency/Consistency_1s_60s.csv",
#         "selectedFeatures": selectedFeatures,
#         "removedFeatures": ["Timestamp", "AttackRatio"],
#     },
# }

In [3]:
parameters = {
    "model": {
        "code": "ARF",
        "parameters": {
            "ensemble_size": 100,
            "max_features": 0.6,
            "lambda_param": 6.0,
            "number_of_jobs": 1,
        },
    },
    "preprocessing": {
        "imputer": "incrementalMean",
        "normalizer": "incrementalZScore",
    },
    "execution": {
        "initialWarmupSize": 2000,
        "metricsWindowSize": 100,
        "seed": 42,
        "generatePlots": True,
        "strictTrainingErrors": False,
    },
}

In [4]:
experimentName = "Classification_Window_DNS-SYN-LDAP"

datasets = {
    f"{scenario}_1s_{blockSeconds}s": {
        "path": f"data/scenario/WIN_DNS-SYN-LDAP/{scenario}/{scenario}_1s_{blockSeconds}s.csv",
        "selectedFeatures": selectedFeatures,
    }
    for scenario in (
        "Consistency",
        "Generalization",
        "Adaptation",
        "Recurrence",
    )
    for blockSeconds in (60, 120, 238)
}

result = ExperimentRunner(task="classification").run(
    experimentName=experimentName,
    datasets=datasets,
    parameters=parameters,
)

display(result["summary"])

================================================================================
[01/12] Experimento=Classification_Window_DNS-SYN-LDAP | Dataset=Consistency_1s_60s
Arquivo: data\scenario\WIN_DNS-SYN-LDAP\Consistency\Consistency_1s_60s.csv
Stream | accuracy=0.9952 | precision=0.9130 | recall=0.8596 | f1=0.8855 | mcc=0.8835

================================================================================
[02/12] Experimento=Classification_Window_DNS-SYN-LDAP | Dataset=Consistency_1s_120s
Arquivo: data\scenario\WIN_DNS-SYN-LDAP\Consistency\Consistency_1s_120s.csv
Stream | accuracy=0.9952 | precision=0.9417 | recall=0.9444 | f1=0.9431 | mcc=0.9405

================================================================================
[03/12] Experimento=Classification_Window_DNS-SYN-LDAP | Dataset=Consistency_1s_238s
Arquivo: data\scenario\WIN_DNS-SYN-LDAP\Consistency\Consistency_1s_238s.csv
Stream | accuracy=0.9924 | precision=0.9565 | recall=0.9479 | f1=0.9522 | mcc=0.9480

================================================================================
[04/12] Experimento=Classification_Window_DNS-SYN-LDAP | Dataset=Generalization_1s_60s
Arquivo: data\scenario\WIN_DNS-SYN-LDAP\Generalization\Generalization_1s_60s.csv
Stream | accuracy=0.9958 | precision=0.9172 | recall=0.8908 | f1=0.9038 | mcc=0.9018

================================================================================
[05/12] Experimento=Classification_Window_DNS-SYN-LDAP | Dataset=Generalization_1s_120s
Arquivo: data\scenario\WIN_DNS-SYN-LDAP\Generalization\Generalization_1s_120s.csv
Stream | accuracy=0.9959 | precision=0.9619 | recall=0.9425 | f1=0.9521 | mcc=0.9500

================================================================================
[06/12] Experimento=Classification_Window_DNS-SYN-LDAP | Dataset=Generalization_1s_238s
Arquivo: data\scenario\WIN_DNS-SYN-LDAP\Generalization\Generalization_1s_238s.csv
Stream | accuracy=0.9930 | precision=0.9658 | recall=0.9475 | f1=0.9566 | mcc=0.9528

================================================================================
[07/12] Experimento=Classification_Window_DNS-SYN-LDAP | Dataset=Adaptation_1s_60s
Arquivo: data\scenario\WIN_DNS-SYN-LDAP\Adaptation\Adaptation_1s_60s.csv
Stream | accuracy=0.9956 | precision=0.9112 | recall=0.8851 | f1=0.8980 | mcc=0.8958

================================================================================
[08/12] Experimento=Classification_Window_DNS-SYN-LDAP | Dataset=Adaptation_1s_120s
Arquivo: data\scenario\WIN_DNS-SYN-LDAP\Adaptation\Adaptation_1s_120s.csv
Stream | accuracy=0.9958 | precision=0.9564 | recall=0.9454 | f1=0.9509 | mcc=0.9487

================================================================================
[09/12] Experimento=Classification_Window_DNS-SYN-LDAP | Dataset=Adaptation_1s_238s
Arquivo: data\scenario\WIN_DNS-SYN-LDAP\Adaptation\Adaptation_1s_238s.csv
Stream | accuracy=0.9935 | precision=0.9619 | recall=0.9577 | f1=0.9598 | mcc=0.9563

================================================================================
[10/12] Experimento=Classification_Window_DNS-SYN-LDAP | Dataset=Recurrence_1s_60s
Arquivo: data\scenario\WIN_DNS-SYN-LDAP\Recurrence\Recurrence_1s_60s.csv
Stream | accuracy=0.9958 | precision=0.9624 | recall=0.9407 | f1=0.9514 | mcc=0.9493

================================================================================
[11/12] Experimento=Classification_Window_DNS-SYN-LDAP | Dataset=Recurrence_1s_120s
Arquivo: data\scenario\WIN_DNS-SYN-LDAP\Recurrence\Recurrence_1s_120s.csv
Stream | accuracy=0.9953 | precision=0.9785 | recall=0.9647 | f1=0.9716 | mcc=0.9690

================================================================================
[12/12] Experimento=Classification_Window_DNS-SYN-LDAP | Dataset=Recurrence_1s_238s
Arquivo: data\scenario\WIN_DNS-SYN-LDAP\Recurrence\Recurrence_1s_238s.csv
Stream | accuracy=0.9931 | precision=0.9827 | recall=0.9721 | f1=0.9774 | mcc=0.9733

,experiment,dataset,model,modelConfig,imputer,normalizer,trainingStrategy,thresholdStrategy,thresholdScoreSource,thresholdScoreLabel,...,tp,tn,fp,fn,accuracy,precision,recall,specificity,f1,mcc
0,Classification_Window_DNS-SYN-LDAP,Consistency_1s_60s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,147,7698,14,24,0.995180,0.913043,0.859649,0.998185,0.885542,0.883501
1,Classification_Window_DNS-SYN-LDAP,Consistency_1s_120s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,323,7701,20,19,0.995163,0.941691,0.944444,0.997410,0.943066,0.940541
2,Classification_Window_DNS-SYN-LDAP,Consistency_1s_238s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,637,7716,29,35,0.992396,0.956456,0.947917,0.996256,0.952167,0.948049
3,Classification_Window_DNS-SYN-LDAP,Generalization_1s_60s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,155,7695,14,19,0.995814,0.917160,0.890805,0.998184,0.903790,0.901751
4,Classification_Window_DNS-SYN-LDAP,Generalization_1s_120s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,328,7702,13,20,0.995907,0.961877,0.942529,0.998315,0.952104,0.950021
5,Classification_Window_DNS-SYN-LDAP,Generalization_1s_238s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,650,7708,23,36,0.992990,0.965825,0.947522,0.997025,0.956586,0.952825
6,Classification_Window_DNS-SYN-LDAP,Adaptation_1s_60s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,154,7694,15,20,0.995560,0.911243,0.885057,0.998054,0.897959,0.895790
7,Classification_Window_DNS-SYN-LDAP,Adaptation_1s_120s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,329,7700,15,19,0.995783,0.956395,0.945402,0.998056,0.950867,0.948682
8,Classification_Window_DNS-SYN-LDAP,Adaptation_1s_238s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,657,7705,26,29,0.993466,0.961933,0.957726,0.996637,0.959825,0.956271
9,Classification_Window_DNS-SYN-LDAP,Recurrence_1s_60s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,333,7696,13,21,0.995783,0.962428,0.940678,0.998314,0.951429,0.949293
10,Classification_Window_DNS-SYN-LDAP,Recurrence_1s_120s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,683,7700,15,25,0.995251,0.978510,0.964689,0.998056,0.971550,0.968989
11,Classification_Window_DNS-SYN-LDAP,Recurrence_1s_238s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,1361,7707,24,39,0.993100,0.982671,0.972143,0.996896,0.977379,0.973328

In [5]:
experimentName = "Classification_Window_UDP-SYN-SSDP"

datasets = {
    f"{scenario}_1s_{blockSeconds}s": {
        "path": f"data/scenario/WIN_UDP-SYN-SSDP/{scenario}/{scenario}_1s_{blockSeconds}s.csv",
        "selectedFeatures": selectedFeatures,
        "removedFeatures": ["Timestamp", "FlowCount"],
    }
    for scenario in (
        "Consistency",
        "Generalization",
        "Adaptation",
        "Recurrence",
    )
    for blockSeconds in (60, 120, 238)
}

result = ExperimentRunner(task="classification").run(
    experimentName=experimentName,
    datasets=datasets,
    parameters=parameters,
)

display(result["summary"])

================================================================================
[01/12] Experimento=Classification_Window_UDP-SYN-SSDP | Dataset=Consistency_1s_60s
Arquivo: data\scenario\WIN_UDP-SYN-SSDP\Consistency\Consistency_1s_60s.csv
Stream | accuracy=0.9937 | precision=0.8735 | recall=0.8333 | f1=0.8529 | mcc=0.8499

================================================================================
[02/12] Experimento=Classification_Window_UDP-SYN-SSDP | Dataset=Consistency_1s_120s
Arquivo: data\scenario\WIN_UDP-SYN-SSDP\Consistency\Consistency_1s_120s.csv
Stream | accuracy=0.9926 | precision=0.9224 | recall=0.9068 | f1=0.9145 | mcc=0.9107

================================================================================
[03/12] Experimento=Classification_Window_UDP-SYN-SSDP | Dataset=Consistency_1s_238s
Arquivo: data\scenario\WIN_UDP-SYN-SSDP\Consistency\Consistency_1s_238s.csv
Stream | accuracy=0.9928 | precision=0.9640 | recall=0.9489 | f1=0.9564 | mcc=0.9525

================================================================================
[04/12] Experimento=Classification_Window_UDP-SYN-SSDP | Dataset=Generalization_1s_60s
Arquivo: data\scenario\WIN_UDP-SYN-SSDP\Generalization\Generalization_1s_60s.csv
Stream | accuracy=0.9952 | precision=0.9053 | recall=0.8743 | f1=0.8895 | mcc=0.8872

================================================================================
[05/12] Experimento=Classification_Window_UDP-SYN-SSDP | Dataset=Generalization_1s_120s
Arquivo: data\scenario\WIN_UDP-SYN-SSDP\Generalization\Generalization_1s_120s.csv
Stream | accuracy=0.9932 | precision=0.9360 | recall=0.9070 | f1=0.9213 | mcc=0.9179

================================================================================
[06/12] Experimento=Classification_Window_UDP-SYN-SSDP | Dataset=Generalization_1s_238s
Arquivo: data\scenario\WIN_UDP-SYN-SSDP\Generalization\Generalization_1s_238s.csv
Stream | accuracy=0.9938 | precision=0.9726 | recall=0.9533 | f1=0.9629 | mcc=0.9595

================================================================================
[07/12] Experimento=Classification_Window_UDP-SYN-SSDP | Dataset=Adaptation_1s_60s
Arquivo: data\scenario\WIN_UDP-SYN-SSDP\Adaptation\Adaptation_1s_60s.csv
Stream | accuracy=0.9947 | precision=0.8807 | recall=0.8807 | f1=0.8807 | mcc=0.8780

================================================================================
[08/12] Experimento=Classification_Window_UDP-SYN-SSDP | Dataset=Adaptation_1s_120s
Arquivo: data\scenario\WIN_UDP-SYN-SSDP\Adaptation\Adaptation_1s_120s.csv
Stream | accuracy=0.9943 | precision=0.9403 | recall=0.9298 | f1=0.9350 | mcc=0.9321

================================================================================
[09/12] Experimento=Classification_Window_UDP-SYN-SSDP | Dataset=Adaptation_1s_238s
Arquivo: data\scenario\WIN_UDP-SYN-SSDP\Adaptation\Adaptation_1s_238s.csv
Stream | accuracy=0.9938 | precision=0.9659 | recall=0.9605 | f1=0.9632 | mcc=0.9598

================================================================================
[10/12] Experimento=Classification_Window_UDP-SYN-SSDP | Dataset=Recurrence_1s_60s
Arquivo: data\scenario\WIN_UDP-SYN-SSDP\Recurrence\Recurrence_1s_60s.csv
Stream | accuracy=0.9942 | precision=0.9501 | recall=0.9153 | f1=0.9324 | mcc=0.9295

================================================================================
[11/12] Experimento=Classification_Window_UDP-SYN-SSDP | Dataset=Recurrence_1s_120s
Arquivo: data\scenario\WIN_UDP-SYN-SSDP\Recurrence\Recurrence_1s_120s.csv
Stream | accuracy=0.9925 | precision=0.9711 | recall=0.9398 | f1=0.9552 | mcc=0.9512

================================================================================
[12/12] Experimento=Classification_Window_UDP-SYN-SSDP | Dataset=Recurrence_1s_238s
Arquivo: data\scenario\WIN_UDP-SYN-SSDP\Recurrence\Recurrence_1s_238s.csv
Stream | accuracy=0.9928 | precision=0.9822 | recall=0.9711 | f1=0.9766 | mcc=0.9724

,experiment,dataset,model,modelConfig,imputer,normalizer,trainingStrategy,thresholdStrategy,thresholdScoreSource,thresholdScoreLabel,...,tp,tn,fp,fn,accuracy,precision,recall,specificity,f1,mcc
0,Classification_Window_UDP-SYN-SSDP,Consistency_1s_60s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,145,7688,21,29,0.993657,0.873494,0.833333,0.997276,0.852941,0.849948
1,Classification_Window_UDP-SYN-SSDP,Consistency_1s_120s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,321,7682,27,33,0.992559,0.922414,0.906780,0.996498,0.914530,0.910677
2,Classification_Window_UDP-SYN-SSDP,Consistency_1s_238s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,669,7687,25,36,0.992753,0.963977,0.948936,0.996758,0.956397,0.952481
3,Classification_Window_UDP-SYN-SSDP,Generalization_1s_60s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,153,7692,16,22,0.995180,0.905325,0.874286,0.997924,0.889535,0.887213
4,Classification_Window_UDP-SYN-SSDP,Generalization_1s_120s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,322,7686,22,33,0.993179,0.936047,0.907042,0.997146,0.921316,0.917876
5,Classification_Window_UDP-SYN-SSDP,Generalization_1s_238s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,674,7691,19,33,0.993822,0.972583,0.953324,0.997536,0.962857,0.959545
6,Classification_Window_UDP-SYN-SSDP,Adaptation_1s_60s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,155,7686,21,21,0.994672,0.880682,0.880682,0.997275,0.880682,0.877957
7,Classification_Window_UDP-SYN-SSDP,Adaptation_1s_120s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,331,7686,21,25,0.994295,0.940341,0.929775,0.997275,0.935028,0.932061
8,Classification_Window_UDP-SYN-SSDP,Adaptation_1s_238s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,680,7685,24,28,0.993822,0.965909,0.960452,0.996887,0.963173,0.959806
9,Classification_Window_UDP-SYN-SSDP,Recurrence_1s_60s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,324,7692,17,30,0.994171,0.950147,0.915254,0.997795,0.932374,0.929507
10,Classification_Window_UDP-SYN-SSDP,Recurrence_1s_120s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,671,7689,20,43,0.992520,0.971056,0.939776,0.997406,0.955160,0.951233
11,Classification_Window_UDP-SYN-SSDP,Recurrence_1s_238s,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,1379,7686,25,41,0.992772,0.982194,0.971127,0.996758,0.976629,0.972376

In [6]:
experimentName = "Classification_FLOW_DNS-SYN-LDAP"

datasets = {
    f"{scenario}_{block}": {
        "path": f"data/scenario/FLOW-DNS-SYN-LDAP/{scenario}/{scenario}_{block}.csv",
        "selectedFeatures": selectedFeatures,
        "removedFeatures": ["Timestamp", "FlowCount"],
    }
    for scenario in (
        "Consistency",
        "Generalization",
        "Adaptation",
        "Recurrence",
    )
    for block in (25, 200, 1000)
}

result = ExperimentRunner(task="classification").run(
    experimentName=experimentName,
    datasets=datasets,
    parameters=parameters,
)

display(result["summary"])

================================================================================
[01/12] Experimento=Classification_FLOW_DNS-SYN-LDAP | Dataset=Consistency_25
Arquivo: data\scenario\FLOW-DNS-SYN-LDAP\Consistency\Consistency_25.csv
Stream | accuracy=0.9991 | precision=0.9091 | recall=0.9333 | f1=0.9211 | mcc=0.9207

================================================================================
[02/12] Experimento=Classification_FLOW_DNS-SYN-LDAP | Dataset=Consistency_200
Arquivo: data\scenario\FLOW-DNS-SYN-LDAP\Consistency\Consistency_200.csv
Stream | accuracy=0.9965 | precision=0.9613 | recall=0.9517 | f1=0.9564 | mcc=0.9546

================================================================================
[03/12] Experimento=Classification_FLOW_DNS-SYN-LDAP | Dataset=Consistency_1000
Arquivo: data\scenario\FLOW-DNS-SYN-LDAP\Consistency\Consistency_1000.csv
Stream | accuracy=0.9936 | precision=0.9817 | recall=0.9810 | f1=0.9813 | mcc=0.9775

================================================================================
[04/12] Experimento=Classification_FLOW_DNS-SYN-LDAP | Dataset=Generalization_25
Arquivo: data\scenario\FLOW-DNS-SYN-LDAP\Generalization\Generalization_25.csv
Stream | accuracy=0.9989 | precision=0.9041 | recall=0.8800 | f1=0.8919 | mcc=0.8914

================================================================================
[05/12] Experimento=Classification_FLOW_DNS-SYN-LDAP | Dataset=Generalization_200
Arquivo: data\scenario\FLOW-DNS-SYN-LDAP\Generalization\Generalization_200.csv
Stream | accuracy=0.9979 | precision=0.9688 | recall=0.9817 | f1=0.9752 | mcc=0.9741

================================================================================
[06/12] Experimento=Classification_FLOW_DNS-SYN-LDAP | Dataset=Generalization_1000
Arquivo: data\scenario\FLOW-DNS-SYN-LDAP\Generalization\Generalization_1000.csv
Stream | accuracy=0.9941 | precision=0.9814 | recall=0.9840 | f1=0.9827 | mcc=0.9791

================================================================================
[07/12] Experimento=Classification_FLOW_DNS-SYN-LDAP | Dataset=Adaptation_25
Arquivo: data\scenario\FLOW-DNS-SYN-LDAP\Adaptation\Adaptation_25.csv
Stream | accuracy=0.9988 | precision=0.8816 | recall=0.8933 | f1=0.8874 | mcc=0.8868

================================================================================
[08/12] Experimento=Classification_FLOW_DNS-SYN-LDAP | Dataset=Adaptation_200
Arquivo: data\scenario\FLOW-DNS-SYN-LDAP\Adaptation\Adaptation_200.csv
Stream | accuracy=0.9975 | precision=0.9623 | recall=0.9783 | f1=0.9702 | mcc=0.9690

================================================================================
[09/12] Experimento=Classification_FLOW_DNS-SYN-LDAP | Dataset=Adaptation_1000
Arquivo: data\scenario\FLOW-DNS-SYN-LDAP\Adaptation\Adaptation_1000.csv
Stream | accuracy=0.9933 | precision=0.9807 | recall=0.9803 | f1=0.9805 | mcc=0.9765

================================================================================
[10/12] Experimento=Classification_FLOW_DNS-SYN-LDAP | Dataset=Recurrence_25
Arquivo: data\scenario\FLOW-DNS-SYN-LDAP\Recurrence\Recurrence_25.csv
Stream | accuracy=0.9981 | precision=0.9362 | recall=0.8800 | f1=0.9072 | mcc=0.9067

================================================================================
[11/12] Experimento=Classification_FLOW_DNS-SYN-LDAP | Dataset=Recurrence_200
Arquivo: data\scenario\FLOW-DNS-SYN-LDAP\Recurrence\Recurrence_200.csv
Stream | accuracy=0.9969 | precision=0.9784 | recall=0.9825 | f1=0.9805 | mcc=0.9788

================================================================================
[12/12] Experimento=Classification_FLOW_DNS-SYN-LDAP | Dataset=Recurrence_1000
Arquivo: data\scenario\FLOW-DNS-SYN-LDAP\Recurrence\Recurrence_1000.csv
Stream | accuracy=0.9938 | precision=0.9897 | recall=0.9892 | f1=0.9894 | mcc=0.9850

,experiment,dataset,model,modelConfig,imputer,normalizer,trainingStrategy,thresholdStrategy,thresholdScoreSource,thresholdScoreLabel,...,tp,tn,fp,fn,accuracy,precision,recall,specificity,f1,mcc
0,Classification_FLOW_DNS-SYN-LDAP,Consistency_25,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,70,13996,7,5,0.999148,0.909091,0.933333,0.999500,0.921053,0.920705
1,Classification_FLOW_DNS-SYN-LDAP,Consistency_200,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,571,14216,23,29,0.996496,0.961279,0.951667,0.998385,0.956449,0.954636
2,Classification_FLOW_DNS-SYN-LDAP,Consistency_1000,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,2943,14459,55,57,0.993605,0.981654,0.981000,0.996211,0.981327,0.977469
3,Classification_FLOW_DNS-SYN-LDAP,Generalization_25,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,66,13995,7,9,0.998863,0.904110,0.880000,0.999500,0.891892,0.891403
4,Classification_FLOW_DNS-SYN-LDAP,Generalization_200,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,589,14009,19,11,0.997949,0.968750,0.981667,0.998646,0.975166,0.974119
5,Classification_FLOW_DNS-SYN-LDAP,Generalization_1000,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,2952,14441,56,48,0.994056,0.981383,0.984000,0.996137,0.982690,0.979103
6,Classification_FLOW_DNS-SYN-LDAP,Adaptation_25,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,67,13995,9,8,0.998793,0.881579,0.893333,0.999357,0.887417,0.886830
7,Classification_FLOW_DNS-SYN-LDAP,Adaptation_200,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,587,14007,23,13,0.997539,0.962295,0.978333,0.998361,0.970248,0.969001
8,Classification_FLOW_DNS-SYN-LDAP,Adaptation_1000,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,2941,14441,58,59,0.993314,0.980660,0.980333,0.996000,0.980497,0.976462
9,Classification_FLOW_DNS-SYN-LDAP,Recurrence_25,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,132,13995,9,18,0.998092,0.936170,0.880000,0.999357,0.907216,0.906697
10,Classification_FLOW_DNS-SYN-LDAP,Recurrence_200,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,1179,14004,26,21,0.996914,0.978423,0.982500,0.998147,0.980457,0.978785
11,Classification_FLOW_DNS-SYN-LDAP,Recurrence_1000,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,5935,14437,62,65,0.993805,0.989661,0.989167,0.995724,0.989414,0.985035

In [7]:
experimentName = "Classification_FLOW_UDP-SYN-SSDP"

datasets = {
    f"{scenario}_{block}": {
        "path": f"data/scenario/FLOW-UDP-SYN-SSDP/{scenario}/{scenario}_{block}.csv",
        "selectedFeatures": selectedFeatures,
        "removedFeatures": ["Timestamp", "FlowCount"],
    }
    for scenario in (
        "Consistency",
        "Generalization",
        "Adaptation",
        "Recurrence",
    )
    for block in (25, 200, 1000)
}

result = ExperimentRunner(task="classification").run(
    experimentName=experimentName,
    datasets=datasets,
    parameters=parameters,
)

display(result["summary"])

================================================================================
[01/12] Experimento=Classification_FLOW_UDP-SYN-SSDP | Dataset=Consistency_25
Arquivo: data\scenario\FLOW-UDP-SYN-SSDP\Consistency\Consistency_25.csv
Stream | accuracy=0.9987 | precision=0.8415 | recall=0.9200 | f1=0.8790 | mcc=0.8792

================================================================================
[02/12] Experimento=Classification_FLOW_UDP-SYN-SSDP | Dataset=Consistency_200
Arquivo: data\scenario\FLOW-UDP-SYN-SSDP\Consistency\Consistency_200.csv
Stream | accuracy=0.9982 | precision=0.9689 | recall=0.9867 | f1=0.9777 | mcc=0.9768

================================================================================
[03/12] Experimento=Classification_FLOW_UDP-SYN-SSDP | Dataset=Consistency_1000
Arquivo: data\scenario\FLOW-UDP-SYN-SSDP\Consistency\Consistency_1000.csv
Stream | accuracy=0.9981 | precision=0.9937 | recall=0.9957 | f1=0.9947 | mcc=0.9935

================================================================================
[04/12] Experimento=Classification_FLOW_UDP-SYN-SSDP | Dataset=Generalization_25
Arquivo: data\scenario\FLOW-UDP-SYN-SSDP\Generalization\Generalization_25.csv
Stream | accuracy=0.9984 | precision=0.8514 | recall=0.8400 | f1=0.8456 | mcc=0.8448

================================================================================
[05/12] Experimento=Classification_FLOW_UDP-SYN-SSDP | Dataset=Generalization_200
Arquivo: data\scenario\FLOW-UDP-SYN-SSDP\Generalization\Generalization_200.csv
Stream | accuracy=0.9979 | precision=0.9734 | recall=0.9750 | f1=0.9742 | mcc=0.9731

================================================================================
[06/12] Experimento=Classification_FLOW_UDP-SYN-SSDP | Dataset=Generalization_1000
Arquivo: data\scenario\FLOW-UDP-SYN-SSDP\Generalization\Generalization_1000.csv
Stream | accuracy=0.9979 | precision=0.9927 | recall=0.9957 | f1=0.9942 | mcc=0.9929

================================================================================
[07/12] Experimento=Classification_FLOW_UDP-SYN-SSDP | Dataset=Adaptation_25
Arquivo: data\scenario\FLOW-UDP-SYN-SSDP\Adaptation\Adaptation_25.csv
Stream | accuracy=0.9980 | precision=0.8052 | recall=0.8267 | f1=0.8158 | mcc=0.8149

================================================================================
[08/12] Experimento=Classification_FLOW_UDP-SYN-SSDP | Dataset=Adaptation_200
Arquivo: data\scenario\FLOW-UDP-SYN-SSDP\Adaptation\Adaptation_200.csv
Stream | accuracy=0.9973 | precision=0.9606 | recall=0.9750 | f1=0.9677 | mcc=0.9664

================================================================================
[09/12] Experimento=Classification_FLOW_UDP-SYN-SSDP | Dataset=Adaptation_1000
Arquivo: data\scenario\FLOW-UDP-SYN-SSDP\Adaptation\Adaptation_1000.csv
Stream | accuracy=0.9979 | precision=0.9924 | recall=0.9957 | f1=0.9940 | mcc=0.9927

================================================================================
[10/12] Experimento=Classification_FLOW_UDP-SYN-SSDP | Dataset=Recurrence_25
Arquivo: data\scenario\FLOW-UDP-SYN-SSDP\Recurrence\Recurrence_25.csv
Stream | accuracy=0.9976 | precision=0.9143 | recall=0.8533 | f1=0.8828 | mcc=0.8821

================================================================================
[11/12] Experimento=Classification_FLOW_UDP-SYN-SSDP | Dataset=Recurrence_200
Arquivo: data\scenario\FLOW-UDP-SYN-SSDP\Recurrence\Recurrence_200.csv
Stream | accuracy=0.9969 | precision=0.9800 | recall=0.9808 | f1=0.9804 | mcc=0.9787

================================================================================
[12/12] Experimento=Classification_FLOW_UDP-SYN-SSDP | Dataset=Recurrence_1000
Arquivo: data\scenario\FLOW-UDP-SYN-SSDP\Recurrence\Recurrence_1000.csv
Stream | accuracy=0.9968 | precision=0.9938 | recall=0.9955 | f1=0.9947 | mcc=0.9924

,experiment,dataset,model,modelConfig,imputer,normalizer,trainingStrategy,thresholdStrategy,thresholdScoreSource,thresholdScoreLabel,...,tp,tn,fp,fn,accuracy,precision,recall,specificity,f1,mcc
0,Classification_FLOW_UDP-SYN-SSDP,Consistency_25,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,69,13987,13,6,0.998650,0.841463,0.920000,0.999071,0.878981,0.879188
1,Classification_FLOW_UDP-SYN-SSDP,Consistency_200,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,592,13981,19,8,0.998151,0.968903,0.986667,0.998643,0.977704,0.976784
2,Classification_FLOW_UDP-SYN-SSDP,Consistency_1000,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,2987,13981,19,13,0.998118,0.993679,0.995667,0.998643,0.994672,0.993530
3,Classification_FLOW_UDP-SYN-SSDP,Generalization_25,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,63,13989,11,12,0.998366,0.851351,0.840000,0.999214,0.845638,0.844835
4,Classification_FLOW_UDP-SYN-SSDP,Generalization_200,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,585,13984,16,15,0.997877,0.973378,0.975000,0.998857,0.974188,0.973081
5,Classification_FLOW_UDP-SYN-SSDP,Generalization_1000,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,2987,13984,22,13,0.997942,0.992689,0.995667,0.998429,0.994175,0.992927
6,Classification_FLOW_UDP-SYN-SSDP,Adaptation_25,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,62,13987,15,13,0.998011,0.805195,0.826667,0.998929,0.815789,0.814861
7,Classification_FLOW_UDP-SYN-SSDP,Adaptation_200,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,585,13978,24,15,0.997329,0.960591,0.975000,0.998286,0.967742,0.966378
8,Classification_FLOW_UDP-SYN-SSDP,Adaptation_1000,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,2987,13979,23,13,0.997883,0.992359,0.995667,0.998357,0.994010,0.992726
9,Classification_FLOW_UDP-SYN-SSDP,Recurrence_25,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,128,13990,12,22,0.997598,0.914286,0.853333,0.999143,0.882759,0.882082
10,Classification_FLOW_UDP-SYN-SSDP,Recurrence_200,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,1177,13978,24,23,0.996908,0.980017,0.980833,0.998286,0.980425,0.978747
11,Classification_FLOW_UDP-SYN-SSDP,Recurrence_1000,ARF,AdaptiveRandomForestClassifier,incrementalMean,IncrementalZScoreNormalizer,all,none,none,none,...,5973,13981,37,27,0.996803,0.993844,0.995500,0.997361,0.994671,0.992388